const rangers = [
  {
    id: 1,
    name: "Jack Landors",
    color: "Red",
    role: "SPD Red Ranger",
    weapon: "Battlizer",
    species: "Human",
    personality: "Fearless and street-smart",
    vehicle: "Delta Runner 1",
    specialPower: "Enhanced combat instincts",
  },
  {
    id: 2,
    name: "Sky Tate",
    color: "Blue",
    role: "SPD Blue Ranger",
    weapon: "Delta Blasters",
    species: "Human",
    personality: "Disciplined and serious",
    vehicle: "Delta Runner 2",
    specialPower: "Force field generation",
  },
  {
    id: 3,
    name: "Bridge Carson",
    color: "Green",
    role: "SPD Green Ranger",
    weapon: "Electro Boomerang",
    species: "Human",
    personality: "Funny and intelligent",
    vehicle: "Delta Runner 3",
    specialPower: "Aura sensing",
  },
  {
    id: 4,
    name: "Z Delgado",
    color: "Yellow",
    role: "SPD Yellow Ranger",
    weapon: "Yellow Blaster",
    species: "Human",
    personality: "Energetic and rebellious",
    vehicle: "Delta Runner 4",
    specialPower: "Duplication ability",
  },
  {
    id: 5,
    name: "Sydney Drew",
    color: "Pink",
    role: "SPD Pink Ranger",
    weapon: "SPD Blaster",
    species: "Human",
    personality: "Stylish and confident",
    vehicle: "Delta Runner 5",
    specialPower: "Molecular manipulation",
  },
  {
    id: 6,
    name: "Sam",
    color: "Omega",
    role: "SPD Omega Ranger",
    weapon: "Omega Morpher",
    species: "Human",
    personality: "Wise and futuristic",
    vehicle: "Omega Cycle",
    specialPower: "Time travel",
  },
  {
    id: 7,
    name: "Doggie Cruger",
    color: "Shadow",
    role: "SPD Shadow Ranger",
    weapon: "Shadow Saber",
    species: "Siriusian",
    personality: "Strict but caring",
    vehicle: "Shadow Raptor",
    specialPower: "Master sword combat",
  },
  {
    id: 8,
    name: "Kat Manx",
    color: "Kat",
    role: "SPD Kat Ranger",
    weapon: "Kat Blaster",
    species: "Cat-like alien",
    personality: "Brilliant and calm",
    vehicle: "Tech Bike",
    specialPower: "Advanced intelligence",
  },
  {
    id: 9,
    name: "Nova Ranger",
    color: "Nova",
    role: "Future SPD Ranger",
    weapon: "Nova Laser",
    species: "Human",
    personality: "Mysterious and skilled",
    vehicle: "Nova Speeder",
    specialPower: "Future tech mastery",
  },
  {
    id: 10,
    name: "A-Squad Red",
    color: "Red",
    role: "A-Squad Leader",
    weapon: "A-Squad Blaster",
    species: "Human",
    personality: "Aggressive and arrogant",
    vehicle: "A-Squad Cycle",
    specialPower: "Advanced combat tactics",
  },
];

export default { rangers };
